/****** Object:  Table [dbo].[APPOINTMENT]    Script Date: 11/21/2018 11:29:01 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APPOINTMENT](
	[IDAppoint] [int] IDENTITY(1,1) NOT NULL,
	[IDClientAppoint] [int] NOT NULL,
	[IDStypeAppoint] [tinyint] NOT NULL,
	[DateAppoint] [datetime] NOT NULL,
	[AddTakeOffAppoint] [bit] NULL,
	[BeginnTimeAppoint] [time](7) NULL,
 CONSTRAINT [PK_APPOINTMENT] PRIMARY KEY CLUSTERED 
(
	[IDAppoint] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[APPOINTMENT]  WITH CHECK ADD  CONSTRAINT [FK_APPOINTMENT_CLIENT] FOREIGN KEY([IDClientAppoint])
REFERENCES [dbo].[CLIENT] ([IDClient])
GO

ALTER TABLE [dbo].[APPOINTMENT] CHECK CONSTRAINT [FK_APPOINTMENT_CLIENT]
GO

ALTER TABLE [dbo].[APPOINTMENT]  WITH CHECK ADD  CONSTRAINT [FK_APPOINTMENT_STYLE] FOREIGN KEY([IDStypeAppoint])
REFERENCES [dbo].[STYLE] ([IDStyle])
GO

ALTER TABLE [dbo].[APPOINTMENT] CHECK CONSTRAINT [FK_APPOINTMENT_STYLE]
GO

