/****** Object:  Table [dbo].[DISCOUNT]    Script Date: 11/21/2018 11:32:52 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DISCOUNT](
	[IDDiscount] [tinyint] IDENTITY(1,1) NOT NULL,
	[TitleDiscount] [varchar](50) NOT NULL,
	[AmountDiscount] [money] NULL,
 CONSTRAINT [PK_DISCOUNT] PRIMARY KEY CLUSTERED 
(
	[IDDiscount] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

