/****** Object:  Table [dbo].[EXTRATSTYLE]    Script Date: 11/21/2018 11:33:21 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EXTRATSTYLE](
	[IDExtratStyle] [int] IDENTITY(1,1) NOT NULL,
	[IDStyle] [tinyint] NOT NULL,
	[IDExtrat] [tinyint] NOT NULL,
 CONSTRAINT [PK_EXTRATSTYLE] PRIMARY KEY CLUSTERED 
(
	[IDExtratStyle] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EXTRATSTYLE]  WITH CHECK ADD  CONSTRAINT [FK_EXTRATSTYLE_EXTRAT] FOREIGN KEY([IDExtrat])
REFERENCES [dbo].[EXTRAT] ([IDExtrat])
GO

ALTER TABLE [dbo].[EXTRATSTYLE] CHECK CONSTRAINT [FK_EXTRATSTYLE_EXTRAT]
GO

ALTER TABLE [dbo].[EXTRATSTYLE]  WITH CHECK ADD  CONSTRAINT [FK_EXTRATSTYLE_STYLE] FOREIGN KEY([IDStyle])
REFERENCES [dbo].[STYLE] ([IDStyle])
GO

ALTER TABLE [dbo].[EXTRATSTYLE] CHECK CONSTRAINT [FK_EXTRATSTYLE_STYLE]
GO

