/****** Object:  Table [dbo].[EXTRAT]    Script Date: 11/21/2018 11:33:05 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EXTRAT](
	[IDExtrat] [tinyint] IDENTITY(1,1) NOT NULL,
	[TitleExtrat] [varchar](50) NULL,
 CONSTRAINT [PK_EXTRAT] PRIMARY KEY CLUSTERED 
(
	[IDExtrat] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

