/****** Object:  Table [dbo].[HAIR]    Script Date: 11/21/2018 11:33:40 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HAIR](
	[IDHair] [int] IDENTITY(1,1) NOT NULL,
	[TitleHair] [varchar](70) NOT NULL,
	[IDProd] [int] NOT NULL,
 CONSTRAINT [PK_HAIR] PRIMARY KEY CLUSTERED 
(
	[IDHair] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[HAIR]  WITH CHECK ADD  CONSTRAINT [FK_HAIR_PRODUCT] FOREIGN KEY([IDProd])
REFERENCES [dbo].[PRODUCT] ([IDProd])
GO

ALTER TABLE [dbo].[HAIR] CHECK CONSTRAINT [FK_HAIR_PRODUCT]
GO

