/****** Object:  Table [dbo].[JOBCONSUMPTION]    Script Date: 11/21/2018 11:33:58 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[JOBCONSUMPTION](
	[IDJobConsump] [int] IDENTITY(1,1) NOT NULL,
	[IDJobDone] [int] NOT NULL,
	[IDHair] [int] NOT NULL,
	[QttyPacks] [tinyint] NOT NULL,
 CONSTRAINT [PK_JOBCONSUMPTION] PRIMARY KEY CLUSTERED 
(
	[IDJobConsump] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[JOBCONSUMPTION]  WITH CHECK ADD  CONSTRAINT [FK_JOBCONSUMPTION_HAIR] FOREIGN KEY([IDHair])
REFERENCES [dbo].[HAIR] ([IDHair])
GO

ALTER TABLE [dbo].[JOBCONSUMPTION] CHECK CONSTRAINT [FK_JOBCONSUMPTION_HAIR]
GO

ALTER TABLE [dbo].[JOBCONSUMPTION]  WITH CHECK ADD  CONSTRAINT [FK_JOBCONSUMPTION_JOBDONE] FOREIGN KEY([IDJobDone])
REFERENCES [dbo].[JOBDONE] ([IDJobDone])
GO

ALTER TABLE [dbo].[JOBCONSUMPTION] CHECK CONSTRAINT [FK_JOBCONSUMPTION_JOBDONE]
GO

