/****** Object:  Table [dbo].[JOBDONE]    Script Date: 11/21/2018 11:34:09 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[JOBDONE](
	[IDJobDone] [int] IDENTITY(1,1) NOT NULL,
	[IDAppoint] [int] NOT NULL,
	[DateJobDone] [datetime] NOT NULL,
	[TimeEndJob] [time](7) NOT NULL,
	[IDDiscount] [tinyint] NULL,
	[DiscountAmount] [money] NULL,
	[feedback] [varchar](150) NULL,
 CONSTRAINT [PK_JOBDONE] PRIMARY KEY CLUSTERED 
(
	[IDJobDone] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[JOBDONE]  WITH CHECK ADD  CONSTRAINT [FK_JOBDONE_APPOINTMENT] FOREIGN KEY([IDAppoint])
REFERENCES [dbo].[APPOINTMENT] ([IDAppoint])
GO

ALTER TABLE [dbo].[JOBDONE] CHECK CONSTRAINT [FK_JOBDONE_APPOINTMENT]
GO

ALTER TABLE [dbo].[JOBDONE]  WITH CHECK ADD  CONSTRAINT [FK_JOBDONE_DISCOUNT] FOREIGN KEY([IDDiscount])
REFERENCES [dbo].[DISCOUNT] ([IDDiscount])
GO

ALTER TABLE [dbo].[JOBDONE] CHECK CONSTRAINT [FK_JOBDONE_DISCOUNT]
GO

