/****** Object:  Table [dbo].[JOBEXECUTER]    Script Date: 11/21/2018 11:34:29 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[JOBEXECUTER](
	[IDJobExecut] [int] IDENTITY(1,1) NOT NULL,
	[IDJobDone] [int] NOT NULL,
	[IDBraider] [int] NOT NULL,
	[BraidingLocat] [char](1) NOT NULL,
 CONSTRAINT [PK_JOBEXECUTER] PRIMARY KEY CLUSTERED 
(
	[IDJobExecut] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[JOBEXECUTER]  WITH CHECK ADD  CONSTRAINT [FK_JOBEXECUTER_BRAIDER] FOREIGN KEY([IDBraider])
REFERENCES [dbo].[BRAIDER] ([IDBraider])
GO

ALTER TABLE [dbo].[JOBEXECUTER] CHECK CONSTRAINT [FK_JOBEXECUTER_BRAIDER]
GO

ALTER TABLE [dbo].[JOBEXECUTER]  WITH CHECK ADD  CONSTRAINT [FK_JOBEXECUTER_JOBDONE] FOREIGN KEY([IDJobDone])
REFERENCES [dbo].[JOBDONE] ([IDJobDone])
GO

ALTER TABLE [dbo].[JOBEXECUTER] CHECK CONSTRAINT [FK_JOBEXECUTER_JOBDONE]
GO

