/****** Object:  Table [dbo].[NEEDPRODUCT]    Script Date: 11/21/2018 11:34:54 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NEEDPRODUCT](
	[IDNeedProd] [int] IDENTITY(1,1) NOT NULL,
	[IDNeed] [int] NOT NULL,
	[IDProd] [int] NOT NULL,
	[QttyNeed] [tinyint] NULL,
	[UnitPrice] [money] NULL,
 CONSTRAINT [PK_NEEDPRODUCT] PRIMARY KEY CLUSTERED 
(
	[IDNeedProd] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[NEEDPRODUCT]  WITH CHECK ADD  CONSTRAINT [FK_NEEDPRODUCT_NEED] FOREIGN KEY([IDNeed])
REFERENCES [dbo].[NEED] ([IDNeed])
GO

ALTER TABLE [dbo].[NEEDPRODUCT] CHECK CONSTRAINT [FK_NEEDPRODUCT_NEED]
GO

ALTER TABLE [dbo].[NEEDPRODUCT]  WITH CHECK ADD  CONSTRAINT [FK_NEEDPRODUCT_PRODUCT] FOREIGN KEY([IDProd])
REFERENCES [dbo].[PRODUCT] ([IDProd])
GO

ALTER TABLE [dbo].[NEEDPRODUCT] CHECK CONSTRAINT [FK_NEEDPRODUCT_PRODUCT]
GO

