/****** Object:  Table [dbo].[NEED]    Script Date: 11/21/2018 11:34:40 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NEED](
	[IDNeed] [int] IDENTITY(1,1) NOT NULL,
	[IDClient] [int] NOT NULL,
	[DateNeed] [date] NULL,
 CONSTRAINT [PK_NEED] PRIMARY KEY CLUSTERED 
(
	[IDNeed] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

