/****** Object:  Table [dbo].[PRODUCT]    Script Date: 11/21/2018 11:35:33 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUCT](
	[IDProd] [int] IDENTITY(1,1) NOT NULL,
	[TitleProd] [varchar](70) NOT NULL,
	[IDTypeProd] [tinyint] NOT NULL,
 CONSTRAINT [PK_PRODUCT] PRIMARY KEY CLUSTERED 
(
	[IDProd] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRODUCT]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCT_TYPEPRODUCT] FOREIGN KEY([IDTypeProd])
REFERENCES [dbo].[TYPEPRODUCT] ([IDTypeProd])
GO

ALTER TABLE [dbo].[PRODUCT] CHECK CONSTRAINT [FK_PRODUCT_TYPEPRODUCT]
GO

