/****** Object:  Table [dbo].[SKILLS]    Script Date: 11/21/2018 11:35:44 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SKILLS](
	[IDSkill] [int] IDENTITY(1,1) NOT NULL,
	[IDBraider] [int] NOT NULL,
	[IDStyle] [tinyint] NOT NULL,
 CONSTRAINT [PK_SKILLS] PRIMARY KEY CLUSTERED 
(
	[IDSkill] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SKILLS]  WITH CHECK ADD  CONSTRAINT [FK_SKILLS_BRAIDER] FOREIGN KEY([IDBraider])
REFERENCES [dbo].[BRAIDER] ([IDBraider])
GO

ALTER TABLE [dbo].[SKILLS] CHECK CONSTRAINT [FK_SKILLS_BRAIDER]
GO

ALTER TABLE [dbo].[SKILLS]  WITH CHECK ADD  CONSTRAINT [FK_SKILLS_STYLE] FOREIGN KEY([IDStyle])
REFERENCES [dbo].[STYLE] ([IDStyle])
GO

ALTER TABLE [dbo].[SKILLS] CHECK CONSTRAINT [FK_SKILLS_STYLE]
GO

