/****** Object:  Table [dbo].[TYPEPRODUCT]    Script Date: 11/21/2018 11:36:11 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TYPEPRODUCT](
	[IDTypeProd] [tinyint] IDENTITY(1,1) NOT NULL,
	[TitleTypeProd] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TYPEPRODUCT] PRIMARY KEY CLUSTERED 
(
	[IDTypeProd] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

