//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectv3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class APPOINTMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPOINTMENT()
        {
            this.JOBDONEs = new HashSet<JOBDONE>();
        }

        public int IDAppoint { get; set; }

        [Display(Name = "Client")]
        public int IDClientAppoint { get; set; }

        [Display(Name = "Style")]
        public byte IDStypeAppoint { get; set; }

        [Display(Name = "Date")]
        public System.DateTime DateAppoint { get; set; }

        [Display(Name = "Add Takeoff?")]
        public Nullable<bool> AddTakeOffAppoint { get; set; }

        public Nullable<System.TimeSpan> BeginnTimeAppoint { get; set; }

        [Display(Name = "Client")]
        public virtual CLIENT CLIENT { get; set; }

        [Display(Name = "Style")]
        public virtual STYLE STYLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOBDONE> JOBDONEs { get; set; }
    }
}
