//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATALOG
    {
        public int IDCatalog { get; set; }
        public int IDVendor { get; set; }
        public int IDProd { get; set; }
        public string UnitType { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual VENDOR VENDOR { get; set; }
    }
}
