//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectv3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinalProjectDBEntities : DbContext
    {
        public FinalProjectDBEntities()
            : base("name=FinalProjectDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<APPOINTMENT> APPOINTMENTs { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BRAIDER> BRAIDERs { get; set; }
        public virtual DbSet<CATALOG> CATALOGs { get; set; }
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<COMPANY> COMPANies { get; set; }
        public virtual DbSet<DESIGNWITH> DESIGNWITHs { get; set; }
        public virtual DbSet<DISCOUNT> DISCOUNTs { get; set; }
        public virtual DbSet<EXTRAT> EXTRATs { get; set; }
        public virtual DbSet<EXTRATSTYLE> EXTRATSTYLEs { get; set; }
        public virtual DbSet<HAIR> HAIR { get; set; }
        public virtual DbSet<JOBCONSUMPTION> JOBCONSUMPTIONs { get; set; }
        public virtual DbSet<JOBDONE> JOBDONEs { get; set; }
        public virtual DbSet<JOBEXECUTER> JOBEXECUTERs { get; set; }
        public virtual DbSet<NEED> NEEDs { get; set; }
        public virtual DbSet<NEEDPRODUCT> NEEDPRODUCTs { get; set; }
        public virtual DbSet<ORDER> ORDERs { get; set; }
        public virtual DbSet<ORDERPRODUCT> ORDERPRODUCTs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<SKILL> SKILLS { get; set; }
        public virtual DbSet<STYLE> STYLEs { get; set; }
        public virtual DbSet<TYPEPRODUCT> TYPEPRODUCTs { get; set; }
        public virtual DbSet<VENDOR> VENDORs { get; set; }
    }
}
