//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEEDPRODUCT
    {
        public int IDNeedProd { get; set; }
        public int IDNeed { get; set; }
        public int IDProd { get; set; }
        public Nullable<byte> QttyNeed { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual NEED NEED { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
