//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectv3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SKILL
    {
        [Display(Name = "Skill ID:")]
        public int IDSkill { get; set; }
        [Display(Name = "Braider ID:")]
        public int IDBraider { get; set; }
        [Display(Name = "Style ID")]
        public byte IDStyle { get; set; }
    
        public virtual BRAIDER BRAIDER { get; set; }
        public virtual STYLE STYLE { get; set; }
    }
}
