//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectv3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class STYLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STYLE()
        {
            this.APPOINTMENTs = new HashSet<APPOINTMENT>();
            this.DESIGNWITHs = new HashSet<DESIGNWITH>();
            this.EXTRATSTYLEs = new HashSet<EXTRATSTYLE>();
            this.SKILLS = new HashSet<SKILL>();
        }
    
        public byte IDStyle { get; set; }
        [Display(Name = "Title Style")]
        public string DesigStyle { get; set; }

        [Display(Name = "Description")]
        public string DescriptStyle { get; set; }

        [Display(Name = "Hair Provided ?")]
        public Nullable<bool> HairProvStyle { get; set; }

        [Display(Name = "Initial Cost")]
        public Nullable<decimal> PriceStyle { get; set; }

        [Display(Name = "Extrat")]
        public Nullable<decimal> PriceExtrat { get; set; }

        [Display(Name = "Picture")]
        public string PictureStyle { get; set; }

        //This was added so the checkboxes work
        //It is not in the database
        public bool isSkill{ get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPOINTMENT> APPOINTMENTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESIGNWITH> DESIGNWITHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXTRATSTYLE> EXTRATSTYLEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SKILL> SKILLS { get; set; }
    }

    public class StyleList
    {
        public List<STYLE> Styles { get; set; }
    }
}
