//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectv3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENDOR()
        {
            this.CATALOGs = new HashSet<CATALOG>();
            this.ORDERs = new HashSet<ORDER>();
        }
    
        public int IDVendor { get; set; }
        public string TitleVendor { get; set; }
        public string PhoneOffice { get; set; }
        public string PhoneCell { get; set; }
        public string StreetVendor { get; set; }
        public string CountyVendor { get; set; }
        public Nullable<short> ZipCodeVendor { get; set; }
        public string StateVendor { get; set; }
        public string EmailVendor { get; set; }
        public string WebSiteVendor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATALOG> CATALOGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERs { get; set; }
    }
}
